apiVersion: v2
name: transmission
description: Transmission bittorrent client Helm Chart
type: application
version: 1.2.0
appVersion: "4.0.4"
dependencies:
  - name: base
    repository: https://charts.damoun.dev
    tags:
      - damoun-base
    version: 1.x.x
maintainers:
  - name: damoun
    email: damien@plenard.me
    url: https://github.com/damoun
