image: "lscr.io/linuxserver/transmission:4.0.4@sha256:05f481660ca7d69f7d7b33906b2143105d0c4e950512af33c0720c5c36ef89e6"
replicaCount: 1

ingress:
  enabled: true
  hostname: transmission.local
  path: /
  pathType: Prefix
  backend:
    servicePort: http

containerPorts:
  http: 9091
  peer: 51413

service:
  type: ClusterIP
  nodePorts: {}
#   http: 9091
#   peer: 51413
  ports:
    http: 9091
    peer: 51413

livenessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistence:
  enabled: false
