image: "lscr.io/linuxserver/transmission:4.0.4@sha256:d468a04d9748c087c94533bc8e5545c068e4715b3e3b85b376ef48606bd17c20"
replicaCount: 1

ingress:
  enabled: true
  hostname: transmission.local
  path: /
  pathType: Prefix
  backend:
    servicePort: http

containerPorts:
  http: 9091
  peer: 51413

service:
  type: ClusterIP
  nodePorts: {}
#   http: 9091
#   peer: 51413
  ports:
    http: 9091
    peer: 51413

livenessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistence:
  enabled: false
