image: "lscr.io/linuxserver/transmission:4.0.4@sha256:bf4313f103377b00c92486d102c2cda28462d4b1bc828bd9df8fc3280b29a605"
replicaCount: 1

ingress:
  enabled: true
  hostname: transmission.local
  path: /
  pathType: Prefix
  backend:
    servicePort: http

containerPorts:
  http: 9091
  peer: 51413

service:
  type: ClusterIP
  nodePorts: {}
#   http: 9091
#   peer: 51413
  ports:
    http: 9091
    peer: 51413

livenessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /transmission/web/
  port: 9091
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistence:
  enabled: false
