apiVersion: v2
name: gickup
description: Gickup cron job Helm Chart
type: application
version: 1.6.0
appVersion: ""
dependencies:
  - name: base
    repository: https://charts.damoun.dev
    tags:
      - damoun-base
    version: 1.x.x
maintainers:
  - name: damoun
    email: damien@plenard.me
    url: https://github.com/damoun
