image: "buddyspencer/gickup:0.10.45@sha256:b4a84f04163099d9f41c648e78a8402d8e6dfe1ece07ccdb3d439543aec5f378"
schedule: "0 0 * * Sun"
persistence:
  enabled: false
secret:
  enabled: false
annotations: {}
