{{- if $.Values.serviceMonitor.enabled }}
{{- range $.Values.serviceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "base.labels.standard" $ | nindent 4 }}
    {{- toYaml $.Values.serviceMonitor.extraLabels | nindent 4 }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: http
    interval: {{ $.Values.serviceMonitor.interval }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    scheme: http
    path: /pve
    params:
      module: [{{ $.Values.serviceMonitor.module }}]
      target: [{{ .url }}]
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: {{ .url }}
      - sourceLabels: [target]
        targetLabel: target
        replacement: {{ .name }}
      {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default dict }}
      - targetLabel: {{ $targetLabel | quote }}
        replacement: {{ $replacement | quote }}
      {{- end }}
{{- if $.Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml $.Values.serviceMonitor.metricRelabelings | indent 4 }}
{{- end }}
  jobLabel: {{ $.Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  selector:
    matchLabels: {{- include "base.labels.matchLabels" $ | nindent 6 }}
{{- if $.Values.serviceMonitor.targetLabels }}
  targetLabels:
{{- range $.Values.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
