apiVersion: v2
name: speedtest-exporter
description: Prometheus Speedtest exporter Helm Chart
type: application
version: 1.0.5
appVersion: "0.0.5"
dependencies:
  - name: base
    repository: https://charts.damoun.dev
    tags:
      - damoun-base
    version: 1.x.x
maintainers:
  - name: damoun
    email: damien@plenard.me
    url: https://github.com/damoun
