image: "ghcr.io/danopstech/speedtest_exporter:v0.0.5@sha256:99efbe55412b0a328d5827fab8dbcc2286093d4ad0d369e4e9b7e3c4153793be"
replicaCount: 1

ingress:
  enabled: false
  hostname: speedtest-exporter.local
  path: /
  pathType: Prefix
  backend:
    servicePort: http

containerPorts:
  http: 9090

annotations: {}

service:
  type: ClusterIP
  nodePorts: {}
#   http: 9090
  ports:
    http: 9090

livenessProbe:
  enabled: true
  path: /health
  port: 9090
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /health
  port: 9090
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

serviceMonitor:
  enabled: false
  interval: 60m
  scrapeTimeout: 60s
