image: "ghcr.io/damoun/omada:v5.9.31@sha256:5c1e60014f537fae4b9f7db0aae21e78666dbdb5cf68e3985175f73983ddf470"
imagePullPolicy: IfNotPresent
replicaCount: 1

ingress:
  enabled: false
  hostname: omada.local
  path: /
  pathType: Prefix
  backend:
    servicePort: https

containerPorts:
  portalHttps: 8043
  discovery: 29810
  adoptV1: 29812
  upgradeV1: 29813
  managerV1: 29811
  managerV2: 29814

service:
  http:
    type: ClusterIP
    nodePorts:
      portalHttps: 8043
    ports:
      portalHttps: 8043
  tcp:
    type: ClusterIP
    nodePorts:
      adoptV1: 29812
      upgradeV1: 29813
      managerV1: 29811
      managerV2: 29814
    ports:
      adoptV1: 29812
      upgradeV1: 29813
      managerV1: 29811
      managerV2: 29814
  udp:
    type: ClusterIP
    nodePorts:
      discovery: 29810
    ports:
      discovery: 29810

livenessProbe:
  enabled: true
  path: /
  port: 8043
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /
  port: 8043
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# mongoUri:
#   secretName:
#   secretKey:
