image: "ghcr.io/damoun/omada:v5.9.31"
imagePullPolicy: IfNotPresent
replicaCount: 1

ingress:
  enabled: false
  hostname: omada.local
  path: /
  pathType: Prefix
  backend:
    servicePort: https

containerPorts:
  https: 8043
  discovery: 29810

service:
  type: ClusterIP
  nodePorts:
    discovery: 29810
  ports:
    https: 8043
    discovery: 29810

livenessProbe:
  enabled: true
  path: /
  port: 8043
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /
  port: 8043
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# mongoUri:
#   secretName:
#   secretKey:
