apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-conf"
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "base.labels.standard" . | nindent 4 }}
data:
  settings.json: {{ toJson .Values.config }}
