apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-ingress
  labels:
    app: transmission

spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission-service
                port:
                  number: 80
