{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "base.labels.standard" . | nindent 4 }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if .Values.ingress.pathType }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  {{- if typeIs "string" .Values.ingress.backend.servicePort }}
                  name: {{ .Values.ingress.backend.servicePort }}
                  {{- else if or (typeIs "int" .Values.ingress.backend.servicePort) (typeIs "float64" .Values.ingress.backend.servicePort) }}
                  number: {{ .Values.ingress.backend.servicePort | int }}
                  {{- end }}
    {{- end }}
  {{- if and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned) }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname | trunc 63 | trimSuffix "-" }}
  {{- end }}
{{- end }}
