apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  labels:
    app: transmission

spec:
  selector:
    app: transmission
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: peer-tcp
      protocol: TCP
      port: 51413
      targetPort: peer-tcp
    - name: peer-udp
      protocol: UDP
      port: 51413
      targetPort: peer-udp
  type: ClusterIP
