apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-cf-pvc
spec:
  storageClassName: transmission-cf-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.config.storage.request }}
