apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-dl-pv
  labels:
    app: transmission
spec:
  capacity:
    storage: {{ .Values.downloads.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: transmission-dl-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.downloads.path }}
    server: {{ .Values.downloads.server }}
