apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-dl-pvc
spec:
  storageClassName: transmission-dl-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.downloads.storage.request }}
