apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-cf-pv
  labels:
    app: transmission
spec:
  capacity:
    storage: {{ .Values.config.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: transmission-cf-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.config.path }}
    server: {{ .Values.config.server }}
