image: "cloudflare/cloudflared:2024.10.0@sha256:060f16531b1ed6dcb382cd2b35d1a845f8dbcb445003b9ec48eef0078cb08bf4"
replicaCount: 2

containerPorts:
  http: 2000

annotations: {}

ingress:
  enabled: false

service:
  type: ClusterIP
  nodePorts: {}
#   http: 2000
  ports:
    http: 2000

env: []
envFrom: []

livenessProbe:
  enabled: true
  path: /healthcheck
  port: 2000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 1
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /ready
  port: 2000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 1
  successThreshold: 1

podMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 30s
