image: "cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0"
replicaCount: 2

containerPorts:
  http: 2000

annotations: {}

ingress:
  enabled: false

service:
  type: ClusterIP
  nodePorts: {}
#   http: 2000
  ports:
    http: 2000

env: []
envFrom: []

livenessProbe:
  enabled: true
  path: /healthcheck
  port: 2000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 1
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /ready
  port: 2000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 1
  successThreshold: 1

podMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 30s
