apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant

spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: {{ .Values.deployment.image }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "200Mi"
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: home-assistant-vol
              mountPath: /config/.storage
            - name: config-volume
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: home-assistant-vol
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: config-volume
          configMap:
            name: home-assistant-config
