apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
spec:
  storageClassName: home-assistant-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.ps.storage.request }}
