apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
  labels:
    app: home-assistant
spec:
  capacity:
    storage: {{ .Values.ps.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: home-assistant-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.ps.path }}
    server: {{ .Values.ps.server }}
