apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service

spec:
  selector:
    app: home-assistant
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
