configmap:
  config:
    data:
      configuration.yaml: |
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - "10.0.0.0/8"

env: []
envFrom: []

image: "ghcr.io/home-assistant/home-assistant:2023.11.2@sha256:400f20c77f52ac31334c1e73a2f19b2d6e5820757d1d476f01960b1efed31949"
imagePullPolicy: IfNotPresent
replicaCount: 1

containerPort: 8123

annotations: {}

schedule: "* * * * *"

service:
  type: ClusterIP
  nodePorts: {}
#   http: 8123
  ports:
    http: 8123

ingress:
  enabled: false
  path: /
  pathType: Prefix
  backend:
    servicePort: http

livenessProbe:
  enabled: false
  path: /
  port: 8123
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: false
  path: /
  port: 8123
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

persistence:
  enabled: false
  path: /config/.storage
  accessModes: [ReadWriteOnce]
