deployment:
  image: "ghcr.io/home-assistant/home-assistant:2023.10.3@sha256:021e2afc6e573a3623dadfe7028e63b370ebc249f3217e1f8fce80ebbfe9afe5"
  replicas: 1

ingress:
  host: hass.local

configmap:
  config:
    data:
      configuration.yaml: |
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - "10.0.0.0/8"
