deployment:
  image: "ghcr.io/home-assistant/home-assistant:2023.9.2@sha256:223c9986ff318eaf35fac70351900cf766c15faf82fbe54150b73b7cfc3c933a"
  replicas: 1

ingress:
  host: hass.local

configmap:
  config:
    data:
      configuration.yaml: |
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - "10.0.0.0/8"
