deployment:
  image: "ghcr.io/home-assistant/home-assistant:2023.9.3@sha256:067490d7b65cfa8b9e494a9447b0e5a7876be83ead7ec01738681c55d66e7cfe"
  replicas: 1

ingress:
  host: hass.local

configmap:
  config:
    data:
      configuration.yaml: |
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - "10.0.0.0/8"
