deployment:
  image: "ghcr.io/home-assistant/home-assistant:2023.4.6"
  replicas: 1

ingress:
  host: hass.local

configmap:
  config:
    data:
      configuration.yaml: |
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - "10.0.0.0/8"
