apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-conf"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "base.labels.standard" . | nindent 4 }}
data:
  conf.yml: {{- toYaml .Values.config | nindent 4 }}
