apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-config"

data:
  conf.yml: |
    source:
      github:
        - token_file: /gickup/secret/github-token.txt
          username: {{ .Values.config.github.username }}
    destination:
      local:
        - path: /github
          bare: true
          zip: true
          structured: true
