apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-conf"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "base.labels.standard" . | nindent 4 }}
data:
  conf.yml: |
  {{- with .Values.config }}
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
