apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-conf"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "base.labels.standard" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  conf.yml: {{- toYaml .Values.config | nindent 4 }}
