apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "base.labels.standard" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
         labels: {{- include "base.labels.standard" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: gickup
              image: {{ .Values.image }}
              volumeMounts:
                - name: gickup-config
                  mountPath: /gickup
                - name: gickup-data
                  mountPath: /data
                - name: secret-volume
                  mountPath: /secret/
                  readOnly: true
          volumes:
            - name: gickup-config
              configMap:
                name: "{{ .Release.Name }}-conf"
            - name: gickup-data
            {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}
            {{- else }}
              emptyDir: {}
            {{ end }}
            - name: gickup-secret
              secret:
                secretName: {{ .Values.secretName }}
