apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "base.labels.standard" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
         labels: {{- include "base.labels.standard" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: gickup
              image: {{ .Values.image }}
              command:
                - /config/conf.yml
              volumeMounts:
                - name: gickup-config
                  mountPath: /config
                - name: gickup-data
                  mountPath: /data
                {{- if .Values.secret.enabled }}
                - name: gickup-secret
                  mountPath: /secret/
                  readOnly: true
                {{ end }}
          volumes:
            - name: gickup-config
              configMap:
                name: "{{ .Release.Name }}-conf"
            - name: gickup-data
            {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}
            {{- else }}
              emptyDir: {}
            {{ end }}
            {{- if .Values.secret.enabled }}
            - name: gickup-secret
              secret:
                secretName: {{ .Values.secret.name }}
            {{ end }}
