apiVersion: v1
kind: PersistentVolume
metadata:
  name: github-backup-pv
  labels:
    app: "{{.Release.Name}}"
spec:
  capacity:
    storage: {{ .Values.pv.github.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: github-backup-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.pv.github.path }}
    server: {{ .Values.pv.github.server }}
