apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-backup-pvc
spec:
  storageClassName: github-backup-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pv.github.storage.request }}
