{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "base.labels.standard" $ | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
  - port: metrics
    interval: {{ .Values.podMonitor.interval }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
    scheme: http
    path: /metrics
{{- if .Values.podMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.podMonitor.metricRelabelings | indent 4 }}
{{- end }}
  jobLabel: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels: {{- include "base.labels.matchLabels" $ | nindent 6 }}
{{- if .Values.podMonitor.targetLabels }}
  targetLabels:
{{- range .Values.podMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end }}
